// Regression tests for stale Tauri/Rust build-cache recovery.
// Run: node --test scripts/build-desktop-retry.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  isStaleTauriCacheError,
  runWithStaleTauriCacheRetry,
} from './build-desktop-retry.mjs';

test('isStaleTauriCacheError recognizes stale Tauri permission cache failures', () => {
  const output = [
    'failed to read plugin permissions: failed to read file',
    "'/Users/alice/old-project/src-tauri/target/release/build/tauri/out/permissions/app/autogenerated/commands/app_hide.toml'",
    'No such file or directory (os error 2)',
  ].join(' ');

  assert.equal(isStaleTauriCacheError(output), true);
});

test('isStaleTauriCacheError ignores unrelated build failures', () => {
  assert.equal(
    isStaleTauriCacheError('error: failed to compile because rustc is missing'),
    false,
  );
});

test('runWithStaleTauriCacheRetry cleans cargo target and retries once for stale Tauri cache', () => {
  const calls = [];
  const result = runWithStaleTauriCacheRetry({
    runTauri: () => {
      calls.push('tauri');
      return calls.length === 1
        ? {
            status: 1,
            output:
              'failed to read plugin permissions from src-tauri/target/release/build/tauri/out/permissions/app/autogenerated/commands/app_hide.toml: No such file or directory (os error 2)',
          }
        : { status: 0, output: 'ok' };
    },
    cleanCargo: () => {
      calls.push('clean');
      return { status: 0, output: 'cleaned' };
    },
    log: () => undefined,
  });

  assert.equal(result.status, 0);
  assert.deepEqual(calls, ['tauri', 'clean', 'tauri']);
});

test('runWithStaleTauriCacheRetry does not clean or retry unrelated failures', () => {
  const calls = [];
  const result = runWithStaleTauriCacheRetry({
    runTauri: () => {
      calls.push('tauri');
      return { status: 1, output: 'ordinary Rust compile failure' };
    },
    cleanCargo: () => {
      calls.push('clean');
      return { status: 0, output: 'cleaned' };
    },
    log: () => undefined,
  });

  assert.equal(result.status, 1);
  assert.deepEqual(calls, ['tauri']);
});

test('runWithStaleTauriCacheRetry can skip stale-cache retry for streaming dev sessions', () => {
  const calls = [];
  const result = runWithStaleTauriCacheRetry({
    runTauri: () => {
      calls.push('tauri-dev');
      return {
        status: 1,
        output:
          'failed to read plugin permissions from src-tauri/target/release/build/tauri/out/permissions/app/autogenerated/commands/app_hide.toml: No such file or directory (os error 2)',
      };
    },
    cleanCargo: () => {
      calls.push('clean');
      return { status: 0, output: 'cleaned' };
    },
    retryOnStaleCache: false,
    log: () => undefined,
  });

  assert.equal(result.status, 1);
  assert.deepEqual(calls, ['tauri-dev']);
});
